### ISSUE TITLE
Error when using encoder in a Model

### ISSUE THREAD

**Issue by Respondi** [gaphex/bert_experimental#8]
Hi i try to use BertLayer encoder and run my model in google colab.
I use tensorflox 1.x

First i clone your github code

!git clone https://github.com/gaphex/bert_experimental

```
sys.path.insert(0, 'bert_experimental')

from bert_experimental.finetuning.text_preprocessing import build_preprocessor
from bert_experimental.finetuning.bert_layer import BertLayer
from bert_experimental.finetuning.modeling import BertConfig, BertModel, build_bert_module
```
When i use the encoder in my model 

```
inp1 = tf.keras.Input(shape=(1,), dtype=tf.string)

encoder = BertLayer(bert_path="./bert-module/", seq_len=48,n_tune_layers=3, do_preprocessing=True,
                             verbose=False, pooling="mean", trainable=True, tune_embeddings=False)

h1 = tf.keras.layers.Dense(50, activation='relu')(encoder(inp1))
```

I have an error : 

---------------------------------------------------------------------------

NameError                                 Traceback (most recent call last)

<ipython-input-12-e9ad4a94d45b> in <module>()
      9 
     10 
---> 11 h1 = tf.keras.layers.Dense(50, activation='relu')(encoder(inp1))
     12 h1 = tf.keras.layers.Dropout(0.1)(h1)
     13 

1 frames

/tensorflow-1.15.2/python3.6/tensorflow_core/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    235       except Exception as e:  # pylint:disable=broad-except
    236         if hasattr(e, 'ag_error_metadata'):
--> 237           raise e.ag_error_metadata.to_exception(e)
    238         else:
    239           raise

NameError: in converted code:
    relative to bert_experimental/bert_experimental/finetuning:

    bert_layer.py:124 call
        pooled = masked_reduce_mean(seq_output, input_mask)
    bert_layer.py:314 masked_reduce_mean
        return tf.reduce_sum(mul_mask(x, m), axis=1) / (

    NameError: name 'mul_mask' is not defined
 
this code run without error in july, now there is a scope pb with mul_mask

Thanks for your help

Luc

**Comment by Ab1992ao** [comment]
Hello, my friend you can create def mul_mask like 272 and put it above
another def like masked reduce mean etc.

Thank you for your msg!

вт, 1 сент. 2020 г., 11:43 Kalaora Luc <notifications@github.com>:

**Comment by Respondi** [comment]
Thanks for your help.
I will do it but i prefer directly use the Class from bert_experimental.finetuning.bert_layer not creating new Class. Could you push the correction?

**Comment by Ab1992ao** [comment]
Yes, of course.

вт, 1 сент. 2020 г., 12:02 Kalaora Luc <notifications@github.com>:

**Comment by Respondi** [comment]
Thanks!

**Comment by Ab1992ao** [comment]
waiting to merge PR with bugfix)

**Comment by Ab1992ao** [comment]
retest)

**Comment by Respondi** [comment]
it's working! thanks

**Comment by Respondi** [comment]
Hi Alexander,

I need your expertise

maybe you could give me the parameters definition :



from bert_experimental.finetuning.bert_layer import BertLayer


encoder = BertLayer(bert_path="./bert-module/", seq_len=48,n_tune_layers=3, do_preprocessing=True,
                             verbose=False, pooling="cls", trainable=True, tune_embeddings=False)

In particular, even with n_tune_layers equal 0 and trainable False, i have a lot of parameters not freezing.
What is tune_embedings ?
Thanks for your answer

Luc Kalaora


________________________________
De : Alexander Abramov <notifications@github.com>
Envoyé : lundi 7 septembre 2020 10:51:14
À : gaphex/bert_experimental
Cc : Luc Kalaora; Author
Objet : Re: [gaphex/bert_experimental] Error when using encoder in a Model (#8)


retest)
